name = "EPGsim"
uuid = "b6a82cc1-40c9-4006-90b7-9176002c0410"
authors = ["aTrotier <a.trotier@gmail.com> and contributors"]
version = "0.1.1"

[compat]
julia = "1.9"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["Test", "ForwardDiff","BenchmarkTools"]
